### ISSUE TITLE
raw JSON causes dual initial entries on datagrid

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#102]
Raw JSON identical to the one defined on form.io, 
However, raw JSON using [form]='...rawJSON...' is rendered differently than src="...formio.url..." 
(with raw JSON, dual initial empty entries are rendered in the datagrid)

For example: use this in the home.html for the ng2-app-starter
```
 <formio src='https://auicqnmuwlxvnoh.form.io/form2'></formio>
  <formio [form]='{"_id":"59227af9ad3ba1005dae9541","machineName":"auicqnmuwlxvnoh:testingTwinDatagridEntry","modified":"2017-05-22T06:24:50.776Z","title":"testing twin datagrid entry","display":"form","name":"testingTwinDatagridEntry","path":"form2","project":"5917b4c2ad3ba1005dae5d21","created":"2017-05-22T05:45:29.834Z","components":[{"input":true,"tree":true,"components":[{"input":true,"tableView":true,"inputType":"text","inputMask":"","label":"name","key":"name","placeholder":"","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"required":false,"minLength":"","maxLength":"","pattern":"","custom":"","customPrivate":false},"conditional":{"show":"","when":null,"eq":""},"type":"textfield","hideLabel":true,"tags":[]}],"tableView":true,"label":"theirdatagrid","key":"theirdatagrid","protected":false,"persistent":true,"hidden":false,"clearOnHide":false,"type":"datagrid","tags":[],"conditional":{"show":"","when":null,"eq":""},"condensed":true,"addAnother":""}],"owner":"589279d62c8ee6006c1e2ed4","submissionAccess":[],"access":[{"type":"read_all","roles":["5917b4c2ad3ba1005dae5d22","5917b4c2ad3ba1005dae5d23","5917b4c2ad3ba1005dae5d24"]}],"tags":[],"type":"form"}'></formio>
```

**Comment by travist** [comment]
Should be fixed in rc15

**Comment by mtsang** [comment]
@travist still seems to be an issue for me with rc15. the above code still shows duplicated fields for the direct JSON

**Comment by mtsang** [comment]
(@travist - may want to reopen the ticket as it's still exhibiting the behaviour)

**Comment by travist** [comment]
Should be fixed in RC18.

**Comment by mtsang** [comment]
unfortunately, not fixed....
