### ISSUE TITLE
Browser console error: TypeError: _i18next2.default.init is not a function

### ISSUE THREAD

**Issue by rmckeel** [formio/ng2-formio#91]
Greetings,

  Great work on FormIO!  I am working on loading a basic JSON schema into an NG2 <formio> component with ng2-formio v1.0.0-rc.10.  I have set up AppConfig with blank appUrl and apiUrl strings.  The form renders (though I haven't yet added the proper stylesheets), however I get this:

```EXCEPTION: Uncaught (in promise): TypeError: _i18next2.default.init is not a function
TypeError: _i18next2.default.init is not a function
    at http://localhost:3000/main.js:4799:27
    at new ZoneAwarePromise (http://localhost:3000/polyfills.js:13646:29)
    at FormioWizard.localize (http://localhost:3000/main.js:4798:14)
    at http://localhost:3000/main.js:12716:23
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:13251:26)
    at Object.onInvoke (http://localhost:3000/vendor.js:25138:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:13250:32)
    at Zone.run (http://localhost:3000/polyfills.js:13043:43)
    at http://localhost:3000/polyfills.js:13630:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:13284:31)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:25129:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:13283:36)
    at Zone.runTask (http://localhost:3000/polyfills.js:13083:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:13463:35)
    at WebSocket.ZoneTask.invoke (http://localhost:3000/polyfills.js:13341:25)```

Main.js:4799 seems to come from  https://formio.github.io/formio.js/docs/file/src/components/base/Base.js.html L245.

Any thoughts on that issue?  This error presented after I loaded in the ng2-formio library and tried to do a basic form output for that specifying the form JSON schema.

**Comment by rmckeel** [comment]
Here's a snapshot of the JavaScript object just before the error presents.

![image](https://cloud.githubusercontent.com/assets/4602573/25873279/1fe45c0c-34cb-11e7-80fb-cfdb9d3a6d76.png)

Also, this maybe related to [this issue](http://stackoverflow.com/q/42477112/3232832), as the question is similar.  I did try updating some of my devDependencies to try to eliminate the possibility of an older TypeScript library or similar causing problems.

```  "devDependencies": {
    "@types/core-js": "~0.9.34",
    "@types/jasmine": "~2.5.36",
    "@types/node": "~6.0.46",
    "@types/request": "0.0.30",
    "autoprefixer": "~6.5.1",
    "copy-webpack-plugin": "~4.0.1",
    "cross-env": "~3.1.3",
    "css-loader": "~0.25.0",
    "del-cli": "~0.2.0",
    "eslint": "~3.10.2",
    "express": "~4.14.0",
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "html-webpack-plugin": "~2.24.1",
    "jasmine-core": "~2.5.2",
    "karma": "~1.3.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-jasmine": "~1.0.2",
    "karma-mocha-reporter": "~2.2.0",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "~1.8.0",
    "minx": "r-park/minx.git",
    "morgan": "~1.7.0",
    "node-sass": "~3.13.0",
    "nodemon": "~1.11.0",
    "npm-run-all": "~3.1.1",
    "postcss-loader": "~1.1.0",
    "raw-loader": "~0.5.1",
    "sass-loader": "~4.0.2",
    "style-loader": "~0.13.1",
    "ts-helpers": "~1.1.2",
    "ts-loader": "2.0.3",
    "tslint": "~3.15.1",
    "typescript": "2.3.2",
    "typings": "~2.1.1",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-server": "2.1.0-beta.4",
    "webpack-md5-hash": "~0.0.5",
    "winston": "~2.3.0"
  }```

**Comment by travist** [comment]
I think you are right on that error. It may be caused by Babel. The core renderer uses Babel to compile, but there are other ways to get the import. I am curious if it works if I use ```require``` vs. ```import```.  Let me create a build of the core renderer which does this to see if that makes a difference.

**Comment by travist** [comment]
So I just did a new build and updated the starterkit app @ https://github.com/formio/ng2-app-starterkit. I did not see this error when walking through this app so I hope it has been fixed. Let me know if it works for you.

Thanks,

Travis.

**Comment by rmckeel** [comment]
@travist Thanks for your quick responses and builds.

I'm not able to test it due to:
```WARNING in ./~/ng2-formio/~/@angular/core/@angular/core.es5.js
5874:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ng2-formio/~/@angular/core/@angular/core.es5.js
5890:15 Critical dependency: the request of a dependency is an expression```

Looks like rc11 removed the ability for it to run on Angular2.

**Comment by travist** [comment]
I removed that because it didn't seem to make a difference (I tested it with a version 2 app and it still pulled in the 4.x versions). Did it work for you when I had that there?

**Comment by rmckeel** [comment]
Yes, it did work as far as I could tell (rc10) and broke again (rc11).  It
allowed me to have Angular2 dependencies and not have issues bringing in
ng2-formio.  It's odd it pulled in 4x versions, hmm.

FYI, I am fairly new to NG2/NG4 (AngularJS I have ~1000 hours in, but it's
a new ballgame with NG2/Webpack/TypeScript/etc!), but all indications seem
that it worked really nicely to have those optional NG2/NG4 dependencies.

From: Travis Tidwell <notifications@github.com> <notifications@github.com>
Reply: formio/ng2-formio
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 10, 2017 at 2:12:36 PM
To: formio/ng2-formio <ng2-formio@noreply.github.com>
<ng2-formio@noreply.github.com>
Cc: Ryan McKeel <ryan@ryanmckeel.com> <ryan@ryanmckeel.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [formio/ng2-formio] Browser console error: TypeError:
_i18next2.default.init is not a function (#91)

I removed that because it didn't seem to make a difference (I tested it
with a version 2 app and it still pulled in the 4.x versions). Did it work
for you when I had that there?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/formio/ng2-formio/issues/91#issuecomment-300598867>,
or mute
the thread

**Comment by travist** [comment]
Ok, I just pushed up an RC13 that I hope fixes this problem for you. I will leave in the dependencies moving forward.

**Comment by rmckeel** [comment]
Thanks!

**Comment by rmckeel** [comment]
@travist I am still getting the JavaScript error `TypeError: _i18next2.default.init is not a function`, I did just update to rc17.  Any thoughts on troubleshooting?  Seems to be coming from FormioWizard.localize, and perhaps some compatibility issue with zone.js.  I have tried zone.js 0.7.7, 0.7.8.

I cannot currently re-start my codebase from the 'starter kit' (mostly because I have some other dependencies requiring NG2 currently, because their NG4 counterparts haven't been ironed out yet).
